### ISSUE TITLE
Cube project with multiple cube tables defined gives weird output

### ISSUE THREAD

**Issue by sam-e-ch** [zazuko/cube-creator#1261] opened 2022-07-05 13:20 UTC
Creating multiple cube tables in one cube project gives weird output, which makes problems with visualize.admin.ch.

Is it even intended to make multiple cube tables per project? If not, I think it should be enforced as otherwise it can lead to confusion.

An example project: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!repro-case-duplicated-cube-wp4gr16r8vy
This leads to errors in the visualizer at https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Frepro_case%2F1?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-umwelt-bafu%22%2C%22subtype%22%3A%22theme%22%2C%22subiri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Fcategory%2Fterritory%22%2C%22includeDrafts%22%3Atrue%7D

If this is intended behavior, I'll open an issue on the visualizer repo, but the text in the cube-creator GUI indicate only one cube table should exist.

**Comment by l00mi** [comment] 2022-07-05 13:53
You are right, it is not intended behaviour. There are still many restrictions which are necessary in cube-creator to be implemented. I will put this one also on the backlog.

**Comment by l00mi** [comment] 2022-07-07 11:40
Yes, not on the project board equals backlog.

**Comment by tpluscode** [comment] 2023-03-08 12:14
Since we do not want to support multiple cubes in a single project, I'm closing this in favour of #1391

**Closed by tpluscode** 2023-03-08 12:14 UTC
Labels: UX
