### ISSUE TITLE
When a transformation is needed, a message was supposed to be displayed to the user ?

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1413] opened 2023-03-30 08:53 UTC
On step 3, when we map a dimension to a Shared Dimension, we then need to go back to Step 2 and transform again, right ?
And we talked about having a user message to inform him when a new transformation is needed, but if I am not mistaken, there is no information displayed after a new Shared Dimension mapping.

Thank you for any input

**Comment by tpluscode** [comment] 2023-04-03 12:31
<img width="523" alt="image" src="https://user-images.githubusercontent.com/588128/229510133-cbea74e3-997e-4f45-8ad3-059931d2a21c.png">

This message should be displayed

**Comment by FabianCretton** [comment] 2023-04-05 05:38
@tpluscode do you mean that this is working, or that this should be done ?
Yesterday Tobias contacted me because of a mapping problem, and it was because he did not run the transform again, so I guess he never saw the message

**Comment by tpluscode** [comment] 2023-04-05 07:21
Yes, this message is already shown after mapping. So unless there are specific circumstances in which it does not, I might assume that Tobias simply missed it

**Comment by FabianCretton** [comment] 2023-04-05 07:45
@tpluscode is the message always present when you re-open the cube, or only just after doing the mapping ?

**Comment by tpluscode** [comment] 2023-04-05 07:46
This message is persistent, displayed in the Cube Designer screen

**Comment by FabianCretton** [comment] 2023-04-05 07:49
So, I did not see the message this morning when opening his cube

**Comment by FabianCretton** [comment] 2023-04-05 07:50
See his cube: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!swissprtronlytrucatedpq2-g21lpjwoq9/metadata
Dimension 'Betriebs ID'
I will ask him to wait before transforming

**Comment by FabianCretton** [comment] 2023-04-05 07:53
Another curiosity, if you look at this:
Very strangely, on that cube, if you open the mapping -> each value has 2 entries, for instance "101", one being mapped, the other one not:
![image](https://user-images.githubusercontent.com/6167669/230016890-e6b14688-da01-418b-8ad3-46f23cf3322b.png)

**Comment by tpluscode** [comment] 2023-04-05 10:50
> Another curiosity, if you look at this:

I found this behaviour being caused by data type of `Betriebs ID`. The mapping itself is `string => shared term` but the IDs are numbers. (The identifiers of that particular dimension are string too, but that may be irrelevant)

Bottom line, I think the mapping should operate on the raw string value of a mapped dimension. @l00mi

**Comment by FabianCretton** [comment] 2023-04-05 10:52
Sorry @tpluscode that we mixed two things in this talk.
I think you talk here about why we see twice each value, right ?

But what about the 'transform' message that do not show up, did you find anything or is it a mistake on my side ?

**Comment by tpluscode** [comment] 2023-04-05 10:55
Yes, I can also confirm that the message did not appear as it should have. Will handle that next.

I focus on the mapping itself because the string vs number mismatch actually breaks the mapping functionality. I mean, yes it would be possible to work around by mapping from CSV to `string` but I think it's an unnecessary restriction

**Comment by FabianCretton** [comment] 2023-04-05 11:00
Thanks, I thus wait for your update

**Comment by tpluscode** [comment] 2023-04-05 14:11
I did find two circumstances when the warning was not displayed: when auto-filling the mapping and when mapped pairs were removed only, without adding any new. Both being fixed now

**Comment by tboeni** [comment] 2023-04-11 09:39
@tpluscode I only just saw this thread. Maybe to give a bit of clarification from my part: It indeed was done via auto-filling the mapping from a shared dimension i created earlier. However when doing the transformation even without the displayed warning message the SD for some reason did not link properly (or at all for that matter). 
This is the [Cube](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!swissprtronlytrucatedpq2-g21lpjwoq9/metadata) in question

**Comment by tpluscode** [comment] 2023-04-11 13:36
Than you for the clarification @tboeni. I believe both your problems will be fixed with next release

**Closed** 2023-04-20 13:25 UTC
Labels: 🐛 bug
