### ISSUE TITLE
Publication job terminated, but "colored pastille" not updated in the interface

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#1168] opened 2022-04-11 09:07 UTC
Running a transformation, the job was finished but the pastille stayed blinking.
When opening the log, i saw that the job was finished, and then, because opening the log i guess, the pastille changed to green.
But switching tabs and coming bac,k to the "publish" tab -> that same job was blinking again

**Comment by l00mi** [comment] 2022-04-11 09:09
@martinmaillard regression?

**Comment by martinmaillard** [comment] 2022-04-11 09:15
I can't reproduce this. Can you provide steps to reproduce?

**Comment by FabianCretton** [comment] 2022-04-11 12:42
I saw it the first time i ran a transformation with the new version, after a while not using the CC, 
Let see if it happens again. In which case I will comment here. Otherwise it was maybe just a one time thing....

**Comment by l00mi** [comment] 2022-04-13 07:05
Okay we close it for now. Please feel free to re-open if it again appears.

**Closed by l00mi** 2022-04-13 07:05 UTC
Labels: 🐛 bug
