### ISSUE TITLE
Nouveau : Internal Server Error - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PDumasBAR** [zazuko/cube-creator#632] opened 2021-03-24 11:30 UTC
Project : [UBD0001 PRTR - Test 03](https://pipelines-integ.lindas.admin.ch/app/cube-projects/cube-project!!ubd0001-prtr-test-03-ar7ejbrmve/edit)

J'ai ajouté 2 descriptions dans les métadonnées du cube et j'obtiens ce message quand je veux sauvegarder :
![image](https://user-images.githubusercontent.com/35593772/112303384-82ab8e00-8c9c-11eb-97c5-ae8908cc1e9c.png)

**Comment by tpluscode** [comment] 2021-03-24 13:03
@PDumasBAR please share what you added to the metadata

**Comment by tpluscode** [comment] 2021-03-24 13:07
Oh, no matter, this same error also happens without changing anything. I'm on it

**Comment by PDumasBAR** [comment] 2021-03-24 15:15
Yes :)
I've made a first input, just DE/EN and try next to complete with more languages with no success.

**Comment by mbch** [comment] 2021-03-26 09:30
Cube markusb_007
Issue: Edit metadata of the cube
Error:
![image](https://user-images.githubusercontent.com/20608869/112611372-0476f500-8e1e-11eb-9449-32cbadd77113.png)

Old bug is not completely solved

**Comment by tpluscode** [comment] 2021-03-29 09:26
Should be fixed as of v1.0.1

**Closed** 2021-03-29 09:27 UTC
Labels: 🐛 bug

**Comment by l00mi** [comment] 2021-03-29 09:48
It is a new error, did you double check?

**Comment by tpluscode** [comment] 2021-03-29 09:55
Yes

**Comment by tpluscode** [comment] 2021-03-29 09:58
Well, at least with the `UBD0001 PRTR - Test 03` cube. 

I can't check with `markusb_007` because the meta is missing the required values. But I'm pretty sure that the cause was all the same

**Comment by l00mi** [comment] 2021-03-29 10:01
:+1:

**Comment by PDumasBAR** [comment] 2021-03-29 10:16
Not sure of the situation (Thursday).
I saw this error in my PRTR. I cannot input the metadata.
You make the correction and it works.
Next day Markus see it the markus_007 the same error, different message.
You can input anything it won't go.

**Comment by l00mi** [comment] 2021-03-29 10:17
@PDumasBAR there was a second fix done.. it should be fixed now.

**Comment by PDumasBAR** [comment] 2021-03-29 10:41
Now ! Now ? or next friday ?

**Comment by mbch** [comment] 2021-03-29 11:07
don't know what has changed but I was able to enter and save the metadata now - Issue solved :)

**Comment by l00mi** [comment] 2021-03-29 11:28
@PDumasBAR it was solved while we were talking.. and also already deployed.

**Comment by PDumasBAR** [comment] 2021-03-29 12:01
Salut Markus,

We talked about this morning.
The dev takes a look, fixes the problem and deployed a new version ☺

A+
Pierre
