### ISSUE TITLE
Cannot delete a cube

### ISSUE THREAD

**Issue by giacomociti** [zazuko/cube-creator#1366] opened 2023-01-31 09:41 UTC
When I try to delete a cube I get a system error. I suspect some data inconsistency because switching to the CSV Mapping or Cube Designer tab I can see an error in the console: 
`Error: targetProperty: Multiple terms found where 0..1 was expected.`
IIRC (but I'm really not sure) the cube was imported from the attached export file 

[Agroscope WebGRUD Module 8 Table 9b.trig.txt](https://github.com/zazuko/cube-creator/files/10544999/Agroscope.WebGRUD.Module.8.Table.9b.trig.txt)

where, in fact, cc:targetProperty has two values

**Comment by tpluscode** [comment] 2023-01-31 11:03
It's interesting that all column mappings have two values of `targetProperty`. This happened only in that single cube

Cannot tell how unless we manage to reproduce. 

Since you only want to delete the project, I propose to fix the delete operation (is should not care about multiple value here)

**Comment by tpluscode** [comment] 2023-03-01 16:04
@giacomociti have you seen this on any other occasion? I propose we close this since the import of a project broken in this way is no longer possible.

When you encounter again a project being exported with duplicates for target property we'll open a new issue and investigate those circumstances.

You probably still need that project removed?

**Closed by tpluscode** 2023-03-01 16:04 UTC
