### ISSUE TITLE
PXCube - Create Project "Request validation error" message

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#765] opened 2021-06-15 06:14 UTC
It did happen once or twice that one pressing the "create project" button, that error message was displayed:
![image](https://user-images.githubusercontent.com/6167669/122002230-c43a6980-cdb1-11eb-8466-dbaec02f49d6.png)

**Comment by martinmaillard** [comment] 2021-06-16 07:50
I was not able to reproduce yet.

**Comment by l00mi** [comment] 2021-06-23 15:00
@FabianCretton does this still not work for you? If it works please close the issue.

**Closed** 2021-07-01 13:00 UTC
Labels: 🐛 bug
