### ISSUE TITLE
Cube Designer - edit dimension metadata - schema.org/about more than 1 value

### ISSUE THREAD

**Issue by FabianCretton** [zazuko/cube-creator#644] opened 2021-03-26 06:35 UTC
With the version 1.0.0, I have this error when editing a dimension metadata of the "Fabian Red List Test 1" project.
It also happens if I change nothing: open the metadata for a dimension and directly click "update dimension metadata"

I do not know if related or could help, but I see that the second columns has two "name" with the "english" tag (do not blame me, it was added by Michael during a discussion :-)). Could it be the reason ? I would say no, as I can open the project, edit another column, and that situation shows up.
![image](https://user-images.githubusercontent.com/6167669/112592075-a8a07200-8e05-11eb-8b5c-4843e78881f0.png)

**Comment by FabianCretton** [comment] 2021-03-26 06:45
Related or not, but still about editing dimension metadata:
I open another project "Fabian Jahrbuch Wald&Holz 2020". 
There is no dimension metadata yet.
I edit the first column, enter an english "Name", save -> the name shows-up in the table (see printscreen), but when I edit once again that dimension, the name do not appear (see printscreen)

![image](https://user-images.githubusercontent.com/6167669/112592937-15683c00-8e07-11eb-8c1f-72ed59229d8d.png)

**Comment by FabianCretton** [comment] 2021-03-26 08:44
Blank node error - maybe useful to debug
![image](https://user-images.githubusercontent.com/6167669/112605685-dbebfc80-8e17-11eb-8509-c284e957ed97.png)

**Comment by tpluscode** [comment] 2021-03-26 12:57
Thank your for reporting this @FabianCretton

Turns out that the issue was related to other reports, caused by unwanted data being stored with the cube metadata. Data which would duplicate certain information but not be updated because it did not really belong there.

This will be fixed once #645 is deployed. 

It will be necessary to open and save the cube metadata, even without making any changes, to ensure that the superfluous data is removed.

**Comment by tpluscode** [comment] 2021-03-26 12:58
The other issue appears to be simply a matter of correctly refreshing the page's data. The dimension is correctly stored and a full page reload can prove that.

I will open a separate issue.

**Closed** 2021-03-29 09:24 UTC
Labels: 🐛 bug
