### ISSUE TITLE
No information available about failed run

### ISSUE THREAD

**Issue by danielmittag** [zazuko/cube-creator#264] opened 2020-12-01 16:52 UTC
I made some (intentionally) wrong definitions in the mapping and started the pipeline job. The pipeline displays full success, but no data is in the preview. Could it be that Stardog push dies quietly (I heard some rumors about that happening when data is not formatted correctly)?

- Job: https://github.com/zazuko/cube-creator/actions/runs/393372414
- Project: https://pipelines-test.lindas.admin.ch/app/cube-projects/cube-project!!dani-udb0037-20201130-what-not-to-do-959mw1de3jl/pipeline

**Comment by martinmaillard** [comment] 2020-12-17 10:39
Is this a duplicate of #276?

**Comment by tpluscode** [comment] 2020-12-17 12:06
I think so

**Comment by l00mi** [comment] 2021-01-10 22:01
Closing this in favor of #276. Description is clearer in #276 and referenced project is gone.

**Closed by l00mi** 2021-01-10 22:01 UTC
